<h1>Post Controller</h1>

<style type="text/css">
    label {
        display: block;
        min-height: 40px;
    }

    span {
        display: inline-block;
        min-width: 100px;
    }
</style>

<?php $this->postForm->prepare(); ?>
<?php echo $this->form()->openTag($this->postForm); ?>
<?php echo $this->formCollection($this->postForm); ?>
<?php echo $this->form()->closeTag(); ?>

<?php Zend\Debug\Debug::dump($this->data); ?>