<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Market\Module'                         => __DIR__ . '/Module.php',
    'Market\Controller\IndexController'     => __DIR__ . '/src/Market/Controller/IndexController.php',
    'Market\Controller\ListingsTableTrait'  => __DIR__ . '/src/Market/Controller/ListingsTableTrait.php',
    'Market\Controller\PostController'      => __DIR__ . '/src/Market/Controller/PostController.php',
    'Market\Controller\ViewController'      => __DIR__ . '/src/Market/Controller/ViewController.php',
    'Market\Factory\IndexControllerFactory' => __DIR__ . '/src/Market/Factory/IndexControllerFactory.php',
    'Market\Factory\ListingsTableFactory'   => __DIR__ . '/src/Market/Factory/ListingsTableFactory.php',
    'Market\Factory\PostControllerFactory'  => __DIR__ . '/src/Market/Factory/PostControllerFactory.php',
    'Market\Factory\PostFilterFactory'      => __DIR__ . '/src/Market/Factory/PostFilterFactory.php',
    'Market\Factory\PostFormFactory'        => __DIR__ . '/src/Market/Factory/PostFormFactory.php',
    'Market\Factory\ViewControllerFactory'  => __DIR__ . '/src/Market/Factory/ViewControllerFactory.php',
    'Market\Form\PostFilter'                => __DIR__ . '/src/Market/Form/PostFilter.php',
    'Market\Form\PostForm'                  => __DIR__ . '/src/Market/Form/PostForm.php',
    'Market\Model\ListingsTable'            => __DIR__ . '/src/Market/Model/ListingsTable.php',
);
