<?php
// Generated by ZF2's ./bin/classmap_generator.php
//Gerado utilizando (dentro da pasta onlinemarket.work/module/Market):
//  php ../../vendor/zendframework/zendframework/bin/classmap_generator.php
return array(
    'Market\Module'                     => __DIR__ . '/Module.php',
    'Market\Controller\IndexController' => __DIR__ . '/src/Market/Controller/IndexController.php',
);
